"""add deployed_at to deployments

Revision ID: 089ac712428d
Revises: 727cd5c5a112
Create Date: 2026-07-10 14:17:56.140441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089ac712428d'
down_revision: Union[str, None] = '727cd5c5a112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'deployed_at')
    # ### end Alembic commands ###
