"""add deployments

Revision ID: 727cd5c5a112
Revises: b6b666f9c826
Create Date: 2026-07-10 14:03:21.195654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727cd5c5a112'
down_revision: Union[str, None] = 'b6b666f9c826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=10), nullable=False),
    sa.Column('software_version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('script_filename', sa.String(length=255), nullable=True),
    sa.Column('script_filepath', sa.String(length=512), nullable=True),
    sa.Column('script_file_size', sa.BigInteger(), nullable=True),
    sa.Column('script_content_type', sa.String(length=128), nullable=True),
    sa.Column('deployed_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deployed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_banks',
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_id', 'bank_id')
    )
    op.create_table('deployment_tasks',
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deployment_id', 'task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployment_tasks')
    op.drop_table('deployment_banks')
    op.drop_table('deployments')
    # ### end Alembic commands ###
